Backend v2
session-foundation/websites pull request #17
Opened 2024-12-28 23:20 UTC by Aerilym

2025-01-05 19:16 UTC, Sophie214wililam2 commented
Hello Can you follow me back

2025-01-08 04:16 UTC, yougotwill requested changes

2025-01-08 22:52 UTC, Aerilym commented on apps/staking/app/mystakes/modules/UnclaimedTokensModule.tsx
>      { enabled }
discussed and resolved

2025-01-08 23:31 UTC, Aerilym commented on apps/staking/lib/constants.ts
>  export const SESSION_NODE_FULL_STAKE_AMOUNT = 20000000000000n;
20_000_000000000n to match the decimals

2025-01-08 23:32 UTC, Aerilym commented on apps/staking/lib/constants.ts
>    CLAIM_REWARDS_AMOUNT = '5000000',
its a decimal so im going to leave it to follow convention

2025-01-08 23:33 UTC, Aerilym commented on apps/staking/lib/constants.ts
> +export const REGISTRATION_LINKS: Partial<Record<REG_TAB, string>> = {
its done in registration v2, this slipped in by mistake

2025-01-08 23:34 UTC, Aerilym commented on apps/staking/components/DevSheet.tsx
> +        result[key] = parseInt(contractId.toString());
correct, its an index

2025-01-08 23:35 UTC, Aerilym commented on apps/staking/components/DevSheet.tsx
> +      address: '0x4abfFB7f922767f22c7aa6524823d93FDDaB54b1',
done

2025-01-08 23:43 UTC, Aerilym commented on apps/staking/components/NodeCard.tsx
> +        'ml-auto flex w-max cursor-pointer select-none items-center align-middle peer-checked:[&>svg]:rotate-180',
fixed

2025-01-08 23:43 UTC, Aerilym commented on apps/staking/components/NodeCard.tsx
> +          'fill-session-text stroke-session-text ml-1 h-4 w-4 transform transition-all duration-300 ease-in-out motion-reduce:transition-none'
fixed

2025-01-08 23:46 UTC, Aerilym commented on apps/staking/app/mystakes/modules/ClaimTokensModule.tsx
> +    <div className="flex flex-col items-center gap-4 text-center">
not sure, why?

2025-01-08 23:47 UTC, Aerilym commented on apps/staking/app/register/[nodeId]/NodeRegistration.tsx
> +    <span>Not Found</span>
This whole things gets replaced in registration v2

2025-01-08 23:47 UTC, Aerilym commented on apps/staking/app/register/[nodeId]/NodeRegistrationForm.tsx
> +        message: 'Invalid Ethereum Address',
All registration stuff is replaced in registration v2, this is just for backwards compatibility while people use backend v2

2025-01-08 23:48 UTC, Aerilym commented on apps/staking/app/register/NodeRegistrations.tsx
> +function ErrorMessage({ refetch }: { refetch: () => void }) {
All registration stuff is replaced in registration v2, this is just for backwards compatibility while people use backend v2

2025-01-08 23:50 UTC, Aerilym commented on apps/staking/app/stake/OpenNodes.tsx
> +    const [err, keySet] = safeTrySync(() => new Set(Object.keys(blsKeysObject)));
Youre right, its not needed, I think it did more at one point while making it, its safe now

2025-01-08 23:51 UTC, Aerilym commented on packages/ui/components/ui/sonner.tsx
> +      <div className="absolute bottom-10 z-[9999999999] mx-6 flex w-[90vw] flex-col items-end gap-2 md:right-14 md:w-auto">
yep

2025-01-08 23:52 UTC, Aerilym commented on apps/staking/components/StakedNode/StakedContractCard.tsx
> +const StakedContractCard = forwardRef<
its not needed i believe but im not gonna go down that rabbit hole yet, will investigate once we're stable

2025-01-08 23:52 UTC, Aerilym commented on apps/staking/components/StakedNode/StakedContractCard.tsx
> +const StakedContractCard = forwardRef<
They havent deprecated the function yet

2025-01-08 23:52 UTC, Aerilym commented on apps/staking/components/StakedNode/StakedContractCard.tsx
> +      collapsableFirstChildren={<></>}
fixed

2025-01-08 23:53 UTC, Aerilym commented on apps/staking/components/StakedNode/StakedContractCard.tsx
> +      className="bottom-4 right-6 flex w-max items-end min-[500px]:absolute"
its the way the grid collapses, will need to clean up break points at some point

2025-01-08 23:56 UTC, Aerilym commented on apps/staking/components/StatusBar.tsx
> +  }, [networkInfo]);
just for you :)

2025-01-08 23:57 UTC, Aerilym commented on apps/staking/app/mystakes/modules/TotalRewardsModule.tsx
> +  const { claimed, status, refetch } = useGetRecipients({ address: address! });
discussed and resolved

2025-01-08 23:57 UTC, Aerilym commented on apps/staking/app/mystakes/modules/UnclaimedTokensModule.tsx
> +            return refetchUnclaimed();
yeah this is fine

2025-01-08 23:57 UTC, Aerilym commented on apps/staking/hooks/useStakes.tsx
> +        address: address!,
yeah all good

2025-01-08 23:58 UTC, Aerilym commented on apps/staking/app/stake/OpenNodes.tsx
> +function ErrorMessage({ refetch }: { refetch: () => void }) {
?

2025-01-08 23:58 UTC, Aerilym commented on apps/staking/app/stake/[address]/NodeStaking.tsx
> +        message: 'Invalid address',
Yeah we dont care about staking and registration v1 anymore, explained in another comment.

2025-01-08 23:59 UTC, Aerilym commented on apps/staking/app/stake/[address]/NodeStaking.tsx
>        <form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col gap-4">
replaced in registration v2

2025-01-09 00:20 UTC, yougotwill approved these changes
LGTM 🚢

2025-01-09 00:20 UTC, yougotwill commented on apps/staking/app/mystakes/modules/ClaimTokensModule.tsx
> +    <div className="flex flex-col items-center gap-4 text-center">
I was just wondering what you expected but it turns out justify-start is the default according to the tailwind docs so all good. Resolving.

2025-01-21 04:13 UTC, merged